Second step
Bizon15100/Project2 pull request #3
Opened 2020-05-14 12:43 UTC by Bizon15100

2020-05-15 19:07 UTC, kkoltun requested changes
Hej!

Dzięki za przesłanie kodu do review. Myślę że jest całkiem spoko, podobają mi się testy parametryczne i obecność buildera. Jest drobniejszych kilka rzeczy do zmiany, najważniejsza to sprawdzanie liczby cyfer po przecinku.

2020-05-15 19:07 UTC, kkoltun commented on src/test/java/com/expenses/ExpenseTest.java
> +    void shouldReturnDatesInRangeOfDates() throws InvalidExpenseException {
Wszystkie testy dotyczące działania `ExpenseService` dobrze byłoby umieścić w klasie `ExpenseServiceTest` :)

2020-05-15 19:07 UTC, kkoltun commented on src/test/java/com/expenses/ExpenseTest.java
> +        assertDoesNotThrow(create);
Tutaj chyba powinina być odwrotna asercja - `assertThrows` :)

2020-05-15 19:07 UTC, kkoltun commented on src/main/java/com/expenses/Expense.java
> +            if (!amountInScale.toString().matches("^(\\d+)\\.(\\d\\d)$|^(\\d+)\\.(\\d)$|^(\\d+)$")) {
Ten regexp wygląda dość skomplikowanie. Jeśli chciałbyś przetestować regexa przed użyciem go, możesz wejść tutaj: https://regexr.com/

2020-05-15 19:07 UTC, kkoltun commented on src/test/java/com/expenses/ExpenseTest.java
> +        Executable createExpenseInFuture = () -> builder().amount(100).date(dateAsNull).place("Market").category("Pizza").build();
Nietrafiona nazwa zmiennej :)

2020-05-16 14:43 UTC, Bizon15100 commented on src/main/java/com/expenses/Expense.java
> +            if (!amountInScale.toString().matches("^(\\d+)\\.(\\d\\d)$|^(\\d+)\\.(\\d)$|^(\\d+)$")) {
Już zmieniłem na wcześniejsze i myślę, że czytelniejsze rozwiązanie.

2020-05-16 14:43 UTC, Bizon15100 commented on src/test/java/com/expenses/ExpenseTest.java
> +        assertDoesNotThrow(create);
Ogarnięte ;)

2020-05-16 14:44 UTC, Bizon15100 commented on src/test/java/com/expenses/ExpenseTest.java
> +    void shouldReturnDatesInRangeOfDates() throws InvalidExpenseException {
Racja, pomyłka w nazwie klasy testowej.

2020-05-16 14:49 UTC, Bizon15100 commented
To w ramach podsumowania, starałem się ogarnąć Buildera (tak by była konieczność jego wykorzystania tworząc pusty konstruktor głównej klasy), Użyłem BigDecimal do kwoty, stworzyłem własny interfejs, nie wiem czy najlepszy na świecie ale ja się świetnie bawię sobie go używając i widząc, że działa. Zajmę się zapisem jak mówiłem raportów w CSV a potem Jsonem ale to już pewnie po niedzieli.

2020-05-16 18:53 UTC, kkoltun commented on src/main/java/com/expenses/Expense.java
> +        public Builder build() throws InvalidExpenseException {
Patrzyłem się na kod i dojrzałem niezbyt zrozumiałą rzecz - czemu metoda build zwraca Buildera, a nie Expense? :)

2020-05-16 18:59 UTC, kkoltun commented on src/main/java/com/expenses/ExpenseCliApp.java
> +                    System.exit(1);
Przekazywanie do `System.exit()` wartości innej niż 0, oznacza że program zakończył działanie błędem. Jest to mechanizm uwarunkowany dość starą "umową" w której systemy operacyjne sprawdzają wartość zwróconą przez zamykający się program.

Tutaj mam taką myśl - albo `System.exit()` który od razu zamknie aplikację, albo `break` - oba raczej nie są potrzebne. Ja bym chyba zostawił `break` bo sam program może chcieć jeszcze coś zrobić, np zapisać dane do pliku zanim się zamknie. `System.exit()` zamknie go natychmiastowo, bez wykonania dalszej części metody.

2020-05-17 06:53 UTC, Bizon15100 commented on src/main/java/com/expenses/Expense.java
> +        public Builder build() throws InvalidExpenseException {
Czy powinienem dla buildera stworzyć tylko charakterystyczne settery a dla Expense gettery? Bo tak będzie działało. Wcześniej nie wpadłem na pomysł z getterami Expense i cały program pobiera Buildera.

2020-05-17 12:04 UTC, closed without merging